server {
    listen 8040; #port we have to listen to
    server_name localhost;
    autoindex off;
		cgi_handler .php .php /path/to/php;
    root ./www;
    index index.htm test.php index.html;
    error_page 404 400 /www/errors/301.html;
    error_page 301 404 /www/errors/345.html;
    client_max_body_size 50;

    location / {
        index index.html test.tm;
        allowed_methods GET;
        autoindex on;
        upload_store ./www/uploads;
    }

    location /upload {
        allowed_methods GET POST DELETE;
        upload_store ./www/uploads;
    }

    location /cgi-bin {
        allowed_methods GET POST;
        upload_store ./www/uploads;
        return  404 http://google.com;
    }

    location /redirect {
        return  404 http://localhost:8080/;
    }
    client_max_body_size 1000000;

}
