# simple config file for testing
# server {
#     listen 8080; #port we have to listen to
#     server_name localhost;

#     root ./www;
#     index index.html;

#     error_page 404 ./www/errors/404.html;
#     client_max_body_size 1000000;

#     location / {
#         methods GET POST;
#         autoindex on;
#     }

#     location /upload {
#         methods GET POST DELETE;
#         upload_store ./www/uploads;
#     }

#     location /cgi-bin {
#         methods GET POST;
#         cgi_path /usr/bin/python3;
#         cgi_ext .py;
#     }

#     location /redirect {
#         return 301 http://localhost:8080/;
#     }
# }

server {
    listen 8040; #port we have to listen to
    server_name localhost;
    root ./www;
    index index.html;
		# location / {
		
    #     methods GET POST;
    #     autoindex on;
    # }
}


# server{listen 8080;server_name localhost;root ./www;index index.html;location / {methods GET POST;autoindex on;}}