# simple config file for testing
server {
    listen 65535; #port we have to listen to
    server_name localhost;
		autoindex off;

    root ./www;
    index index.htm test.php index.html;

    error_page 404 300 123 ./www/errors/404.html;
    client_max_body_size 1000000;

    location / {
      	# limit_except GET POST;
        # autoindex on;
				upload_store ./www/uploads;
    }

    location /upload {
        # limit_except GET POST DELETE;
        upload_store ./www/uploads;
    }

    location /cgi-bin {
        # limit_except GET POST;
				upload_store ./www/uploads;
    }

    location /redirect {
        return http://localhost:8080/;
    }
}

# server {
#     listen 8040; #port we have to listen to
#     server_name localhost;
#     root ./www;
#     index index.html;
# 		client_max_body_size 30000;
# 		location / {
#       # methods GET POST;
#       autoindex on;
#     }
# }

# server{listen 8080;server_name localhost;root ./www;index index.html;location / {methods GET POST;autoindex on;}}