# simple config file for testing
# error codes handled: 400, 403, 404, 405, 408, 413, 500, 505

server {
    listen 8040; #port we have to listen to
    listen 8080;
    server_name localhost;
		autoindex on;
		cgi_handler .php /path/to/interpreter;
		cgi_handler .php /path/to/interpreter;
		cgi_handler .php /path/to/interpreter;
		cgi_handler .php /path/to/interpretdsf;
		error_page 505 /www/errors/505.html;

    root ./data/www;
    index index.htm test.php index.html;
   
    client_max_body_size 2147483647;

    location / {
				index index.html secret.html;
      	allowed_methods GET;
        autoindex on;
				upload_store ./www/uploads;
				error_page 505 /www/errors/505.html;
				error_page 403 404 /www/errors/345.html;
    }

    location /upload {
        allowed_methods GET POST DELETE;
        upload_store ./www/uploads;
    }

    location /cgi-bin {
        allowed_methods GET POST;
				upload_store ./www/uploads;
				return  404 http://google.com;
				cgi_handler .php /path/to/interpreter;
    }

    location /redirect {
        return  404 http://localhost:8080/;
    }
		client_max_body_size 1000000;

    location /images {
      # root ./www/blablabla;
      allowed_methods GET;
    }

    location /images/icons {
      allowed_methods GET POST;
      root /var/www/images;
    }

}


server {
    listen 8041; #port we have to listen to
    server_name test;
    root ./www/test;
    index index.html index.htm;
		client_max_body_size 30000;
		location / {
      # methods GET POST;
      autoindex on;
    }
}

server{listen 8081;server_name localhosting;root ./www;index index.html;location / {allowed_methods GET POST;autoindex on;}}
