name: CI
run-name: ${{ github.actor }} is building the webserv

on:
  push:
  pull_request:

jobs:
  build-webserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check compiler
        run: |
          c++ --version
          c++ -v

      - name: Build Web Server
        run: make

      - name: Verify that executable exists
        run: |
          if [ -f webserv ]; then
            echo "✅ Executable built successfully"
          else
            echo "❌ Executable not found"
            exit 1
          fi
  
  tests-http:
    if: |
      (github.event_name == 'push' && github.ref_name == 'http') ||
      (github.event_name == 'pull_request' && github.head_ref == 'http')
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check compiler
        run: |
          c++ --version
          c++ -v


      - name: Build Google Tests on Http Parser
        run: make tests_http_parser

      - name: Run Google Tests on Http Parser
        run: ./http_gtests --gtest_color=yes

      - name: Build Google Tests on Router
        run: make tests_router

      - name: Run Google Tests on Router
        run: ./router_gtests --gtest_color=yes