name: Build
run-name: ${{ github.actor }} is building the webserv

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: make

      - name: Verify that executable exists
        run: |
          if [ -f webserver ]; then
            echo "✅ Executable built successfully"
          else
            echo "❌ Executable not found"
            exit 1
          fi
